# Title of the page
title: "Brief History of Neurotechnology"
# Your name
author: NTMC
# Show a link to LinkedIn in the header intro. Comment out to disable.
linkedin: https://www.linkedin.com/company/neurotechmc/about/
# Show a link at the top of your timeline to your main personal site
# Comment this out to disable
personal_site:
  url: https://neurotechmicrocreds.com/
  #title: neil.gg
# show today marker at end of timeline
#show_today: true

# Your timeline is split into periods (e.g., decades, childhood/teens/adult, "Before Timeliner"/"After Timeliner", etc)
# Each period has a list of events formatted as `- date: title`. If you don't want to have period dividers, leave out the name field.
periods:
  - name: Magnetic Resonance Imaging (MRI)
    events:
    - 1938: >-
        <b>Isidor Isaac Rabi</b> first detects the phenomenon of nuclear magnetic resonance (NMR), the underlying principles used in MRI,
        in a beam of lithium chloride through a complex experimental procedure 
        <a href="https://doi.org/10.1103/PhysRev.53.318" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 1946: "<b>Felix Bloch</b> & <b>Edward Mills Purcell</b> extend the work done by <b>Rabi</b> by developing new methods for obtaining precise measurements
    from nuclear magnetization in solids and liquids. Bloch & Purcell shared the Nobel Prize in Physics for this work in 1952."
    - 1971: >-
        <b>Raymond Damadian</b> shows MR relaxation time could be used to distinguish cancer from healthy tissue, being the first to identify 
        the clinical use of NMR <a href="https://doi.org/10.1126/science.171.3976.1151" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 1973: >-
        <b>Paul C. Lauterbur</b> develops the theory for MRI by proposing the use of magnetic field gradients to encode spatial information 
        from the NMR signal <a href="https://doi.org/10.1038/242190a0" target="_blank" rel="noopener">(Link to original paper)</a>. 
        He recieved the Nobel Prize in Physiology or Medicine in 2003 jointly with <b>Peter Mansfield</b>.
    - 1974: "<b>Damadian</b> designs and builds the first full-body MRI machine, called 'Indomitable'."
    - 1977: >-
        <b>Damadian</b>, <b>Larry Minkoff</b>, and <b>Michael Goldsmith</b> perform the first MRI scan on a live animal to visualize a tumour
        <a href="https://doi.org/10.1126/science.1006309" target="_blank" rel="noopener">(Link to original paper)</a>, 
        and MRI body scan of a human <a href="https://doi.org/10.1038/270722a0" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 1977: >-
        <b>Peter Mansfield</b> invents an MRI acquisition method that makes scan times suitable for clinical use, called echo planar imaging (EPI)
        <a href="https://iopscience.iop.org/article/10.1088/0022-3719/10/3/004" target="_blank" rel="noopener">(Link to original paper)</a>. 
        He recieved the Nobel Prize in Physiology or Medicine in 2003 jointly with <b>Lauterbur</b>.
    - 1978: "<b>Damadian</b> found FONAR corporation, which produced the first commercially available MRI machine in 1980."
    - 1986-1987: "<b>Charles Dumulin</b> & <b>Howard Hart</b> develop MR angiography, where vasculature can be imaged using MRI. 
    Additionally, <b>Denis Le Bihan</b> obtained the first diffusion MR images."
    - 1990: >-
        <b>Seiji Ogawa</b> recognizes deoxyhemoglobin and oxyhemoglobin have different magnetic properties, and discovered the technique that
        underlies functional MRI (fMRI) <a href="https://doi.org/10.1073/pnas.87.24.9868" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 2012: >-
        Animal studies are performed using a magnet strength of 21.1 Tesla <a href="https://doi.org/10.1016%2Fj.jmr.2012.05.016" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 2019: >-
        For the first time, human studies were performed using a magnet strength of 10.5 Tesla
        <a href="https://doi.org/10.1002%2Fmrm.28093" target="_blank" rel="noopener">(Link to original paper)</a>.
    - 2020: "Hyperfine protable MR imaging system becomes the first FDA approved portable MRI system capable of providing neuroimaging at the 
    bedside, eliminating the need for patients to be moved to a specialized MR suite."
  - name: X-ray & Computed Tomography (CT)
    events:
    - 1895: >-
        <b>Wilhelm Roentgen</b> finds that cathode rays are able to pass through human tissue and visualize underlying anatomy, 
        giving rise to clinical X-ray imaging or radiography 
        <a href="https://www.aps.org/publications/apsnews/200111/history.cfm" target="_blank" rel="noopener">(Link for more details)</a>. 
        For this work he recieved the Novel Prize in Physics in 1901.
    - 1913: >-
        <b>William David Coolidge</b> designs a high vacuum X-ray tube that was a reliable sources of X-rays and could operate at 
        energies up to 100,000 volts. This work overcame technological issues in previous X-ray tubes that often broke down at high voltages. 
    - 1917: >-
        <b> Johann Radon</b> develops the mathematical theory behind CT by showing an object can be reconstructed based on an infinite set
        of its projections, known as the Radon transform.
    - 1961: >-
        <b>William Oldendorf</b> theorizes the ability to scan a head through the use of a transmitted beam of X-rays in conjunction with the 
        Radon transform, creating an apparatus that has a rotating source and coupled detector that could get X-ray images of various materials.
    - 1967: >-
        <b>Godfrey Newbold Jounsfield</b> extends the theory for CT by taking several X-ray images at different angles followed by computer reconstruction,  
        also inventing the first commercially available CT scanner. For this work he recieved the Nobel Prize in Physiology or Medicine in 1979. 
    - 1971: >-
        In London, England, a CT scanner is used clinically to image a women suspected to have a brain tumour.
  - name: 2010's
    events:
    - June 2010: "✈️ Neil spends a summer in Paris for study abroad."
    - October 2010: 🎂 Neil turns 20.
    - October 2011: 🏆 Neil becomes a ThinkChicago Fellow.
    - December 2011: >-
        💻 Neil works with <a href="https://vimeo.com/33098706" target="_blank" rel="noopener" title="Watch a slideshow of
        my team's trip to Haiti">Haiti's Ministry of Education, OLPC, and IIT</a> to deploy solar panels, laptops, and servers pre-loaded with
        Wikipedia in a Haitian school.
    - May 2012: >-
        🎓 Neil graduates from Illinois Institute of Technology with degrees in Computer Science & Psychology, a minor in Entrepreneurship,
        and a specialization in Artificial Intelligence.
    - June 2012: "👨‍💻 Neil cofounds Tabule, a smart student planner powered by AI."
    - July 2012: >-
        🎙 Neil does a <a href="https://vimeo.com/45029595" target="_blank" rel="noopener">press conference with Rahm Emanuel</a> about Tabule and
        Chicago tech. Emanuel says "Chicago needs more Neils." Neil agrees for exactly 3 years.
    - August 2014: >-
        👨‍💻 Neil builds the <a href="https://www.youtube.com/watch?v=oo6b5gZqm0A" target="_blank" rel="noopener" title="Watch the
        Flocks in action">Flocks</a>, an IoT art installation that reacts to its environment and Twitter. Cisco displays two at their Internet of Things
        conference.
    - December 2014: >-
        👨‍💻 Neil works with Eren Bali to prototype Maven, the operating system for your business.
    - July 2015: 🤕 Neil gets hit by a bicyclist named Neil G. He wakes up in the hospital with 14 stitches on his face but no new superpowers.
    - November 2015: 🏠 Neil buys his first home in South Loop.
    - January 2018: 🧠 Neil builds an AI to manage his home for him.
    - September 2018: 🛠 Neil turns his second bedroom into a prototyping lab with four 3D printers and a soldering bench.
    - January 2019: 🏆 Neil receives a grant from Y Combinator to keep building his smart home tech.
    - April 2019: >-
        👨‍💻 Neil founds <a href="https://hiome.com" target="_blank" rel="noopener">Hiome</a> to change how we use our homes.
  - name: 2020's
    events:
    - May 2020: >-
        🦠 Neil launches <a href="https://researchexplained.neil.gg" target="_blank" rel="noopener">Research Explained</a> to make visual
        summaries of COVID-19 research accessible to anyone.
    - October 2020: 🎂 Neil turns 30 in the midst of a global pandemic.
    - April 2021: 🏠 Neil moves to a new home in Streeterville.
    - May 2021: 🐶 Neil's sister adopts <a href="https://photos.neil.gg/wally" target="_blank" title="Meet our beautiful greyhound!">Wally</a>, fulfilling a life-long Gupta sibling dream and granting him unlimited dog time with none of the work.
